---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ovn-openstack-org-v1beta1-ovncontroller
  failurePolicy: Fail
  name: movncontroller-v1beta1.kb.io
  rules:
  - apiGroups:
    - ovn.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ovncontrollers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ovn-openstack-org-v1beta1-ovndbcluster
  failurePolicy: Fail
  name: movndbcluster-v1beta1.kb.io
  rules:
  - apiGroups:
    - ovn.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ovndbclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ovn-openstack-org-v1beta1-ovnnorthd
  failurePolicy: Fail
  name: movnnorthd-v1beta1.kb.io
  rules:
  - apiGroups:
    - ovn.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ovnnorthds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ovn-openstack-org-v1beta1-ovncontroller
  failurePolicy: Fail
  name: vovncontroller-v1beta1.kb.io
  rules:
  - apiGroups:
    - ovn.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ovncontrollers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ovn-openstack-org-v1beta1-ovndbcluster
  failurePolicy: Fail
  name: vovndbcluster-v1beta1.kb.io
  rules:
  - apiGroups:
    - ovn.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ovndbclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ovn-openstack-org-v1beta1-ovnnorthd
  failurePolicy: Fail
  name: vovnnorthd-v1beta1.kb.io
  rules:
  - apiGroups:
    - ovn.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ovnnorthds
  sideEffects: None
