# permissions for end users to view ovsdbservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovsdbserver-viewer-role
rules:
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovsdbservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovsdbservers/status
  verbs:
  - get
