## Append samples you want in your CSV to this file as resources ##
resources:
- ovn_v1alpha1_ovncentral.yaml
- ovn_v1alpha1_ovsdbserver.yaml
- ovn_v1alpha1_ovsdbcluster.yaml
- ovn_v1alpha1_ovnnorthd.yaml
- ovn_v1alpha1_ovndbcluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
