apiVersion: ovn.openstack.org/v1beta1
kind: OVNCentral
metadata:
  name: ovncentral-sample
spec:
  replicas: 1
  nbReplicas: 1
  sbReplicas: 1
  image: quay.io/mbooth/ovn-central:trunk
  storageSize: 1G
