apiVersion: ovn.openstack.org/v1beta1
kind: OVSDBCluster
metadata:
  name: ovsdbcluster-sample
spec:
  dbType: NB
  replicas: 1
  clientConfig: ovsdbcluster-sample
  image: quay.io/mbooth/ovn-central:trunk
  serverStorageSize: 10Gi
